[package]
name = "dht"
description = "Implementation of the bittorrent mainline DHT"
keywords = ["dht", "distributed", "hash", "mainline", "bittorrent"]
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
bencode = { path = "../bencode" }
handshake = { path = "../handshake" }
util = { path = "../util" }

crc = "3"
log = "0.4"
mio = "0.8"
rand = "0.8"
chrono = "0.4"
error-chain = "0.12"
