[package]
description = "Implementation of the bittorrent mainline DHT"
keywords = ["bittorrent", "dht", "distributed", "hash", "mainline"]
name = "dht"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
bencode = { path = "../bencode" }
handshake = { path = "../handshake" }
util = { path = "../util" }

chrono = "0.4"
crc = "3"
error-chain = "0.12"
log = "0.4"
mio = "1.0"
rand = "0.8"
