[package]
name = "dht"
description = "Implementation of the bittorrent mainline DHT"
keywords = ["dht", "distributed", "hash", "mainline", "bittorrent"]

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
bencode = { path = "../bencode" }
handshake = { path = "../handshake" }
util = { path = "../util" }

crc = "1.2.0"
log = "0.3.0"
mio = "0.5.0"
rand = "0.8.5"
chrono = "0.2.0"
error-chain = "0.12"
