[package]
description = "Implementation of the bittorrent mainline DHT"
keywords = ["bittorrent", "dht", "distributed", "hash", "mainline"]
name = "dht"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
bencode = { path = "../bencode" }
handshake = { path = "../handshake" }
util = { path = "../util" }

chrono = "0"
crc = "3"
futures = "0"
rand = "0"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
tracing = "0"
tracing-subscriber = "0"
