[package]
name = "magnet"
version = "0.0.3"
description = "Magnet link parsing and construction"
keywords = ["magnet", "bittorrent"]

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
license-file.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
util = { path = "../util" }
url = "^0.5.7"
base32 = "^0.3.1"
