[package]
description = "Common handshaking interface as well as a default handshake implementation"
keywords = ["bittorrent", "handshake"]
name = "handshake"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
util = { path = "../util" }

bytes = "1"
futures = "0"
nom = "8"
pin-project = "1"
rand = "0"
tokio = { version = "1", features = ["full"] }
tracing = "0"

[dev-dependencies]
tracing-subscriber = "0"
