[package]
name = "select"
version = "0.1.0"
description = "Bittorrent Infrastructure Project Piece Selection Module"
keywords = ["piece", "selection"]

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
license-file.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true

[dependencies]
handshake = { path = "../handshake" }
util = { path = "../util" }
peer = { path = "../peer" }
metainfo = { path = "../metainfo" }
utracker = { path = "../utracker" }

bit-set = "0.4"
bytes = "0.4"
error-chain = "0.11"
futures = "0.1"
rand = "0.3"
log = "0.3"

[dev-dependencies]
futures-test = { git = "https://github.com/carllerche/better-future.git" }
