[package]
description = "Bittorrent Infrastructure Project Piece Selection Module"
keywords = ["piece", "selection"]
name = "select"
readme = "README.md"

authors.workspace = true
categories.workspace = true
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish.workspace = true

repository.workspace = true
version.workspace = true

[dependencies]
handshake = { path = "../handshake" }
metainfo = { path = "../metainfo" }
peer = { path = "../peer" }
util = { path = "../util" }
utracker = { path = "../utracker" }

bit-set = "0"
bytes = "1"
futures = "0"
rand = "0"
thiserror = "2"
tracing = "0"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tracing-subscriber = "0"
